version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "04:20"
    open-pull-requests-limit: 10
    target-branch: main
    labels:
      - "dependency"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    auto-merge:
      enabled: true
      method: squash
