input_dir: "input"
file_name_base: "gribweather2days"
batch_size: 1000
log_file: "logs/weather_processing.log"

# Optional: Specify file format explicitly
# If not specified, the processor will auto-detect
# file_format: "netcdf"  # "netcdf", "grib", or "auto"

# GRIB-specific settings (optional)
grib_settings:
  # Variable name mappings if your GRIB file uses different names
  # The converter will try common names automatically, but you can override here
  variable_mapping:
    t2m: ["t2m", "2t", "T_2M", "TMP_2maboveground"]
    u100m: ["u100", "u100m", "U_100M", "100u", "UGRD_100maboveground"]
    v100m: ["v100", "v100m", "V_100M", "100v", "VGRD_100maboveground"]
    ssrd: ["ssrd", "ssr", "DSWRF_surface", "surface_downwelling_shortwave_flux"]
    fdir: ["fdir", "direct_normal_irradiance", "DNI", "direct_solar"]
  # Coordinate names (usually automatic detection works)
  coordinate_names:
    latitude: ["latitude", "lat", "y"]
    longitude: ["longitude", "lon", "x"]
    time: ["time", "valid_time", "forecast_time"]

# Database settings
db_user: "postgres"
db_password: "postgres"
db_port: 5432
db_name: "gribweather2days"